spring.application.name=backend

spring.couchbase.connection-string=127.0.0.1
spring.couchbase.username=Administrator
spring.couchbase.password=123456
spring.data.couchbase.bucket-name=first_bucket

spring.data.couchbase.auto-index=true









#spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect
#
## Swagger UI
#springfox.documentation.swagger-ui.enabled=true
#
## Spring Security
#spring.security.user.name=stefi
#spring.security.user.password=parola
#
## Logging
#logging.file.name=C:\project\new_project\Proiect_nou\myLogs.log
#
## Session timeout
#server.servlet.session.timeout=1m
#
## Couchbase configuration
#spring.couchbase.connection-string=127.0.0.1
#spring.couchbase.username=Administrator
#spring.couchbase.password=123456
#spring.data.couchbase.bucket-name=first_bucket
#
##Specify the custom configuration class for couchbase
#spring.data.couchbase.auto-index=true


